#' Plot EWMA Chart
#'
#' @param sim_data A data frame generated by simulate_epc_spc() or apply_system()
#' @return A ggplot object
#' @export
plot_ewma <- function(sim_data) {
  requireNamespace("ggplot2", quietly = TRUE)

  # Safely handle column names for ggplot2 using the .data pronoun
  y_col <- if("EWMA" %in% names(sim_data)) "EWMA" else "SPC_Statistic"

  # Determine target line for the dashed line
  target_line <- if(mean(sim_data$UCL) > 10) mean(c(sim_data$UCL[1], sim_data$LCL[1])) else 0

  ggplot2::ggplot(sim_data, ggplot2::aes(x = Time, y = .data[[y_col]])) +
    ggplot2::geom_line(color = "darkblue") +
    ggplot2::geom_hline(yintercept = sim_data$UCL[1], color = "black", linewidth = 1) +
    ggplot2::geom_hline(yintercept = sim_data$LCL[1], color = "black", linewidth = 1) +
    ggplot2::geom_hline(yintercept = target_line, color = "black", linetype = "dashed") +
    ggplot2::geom_point(data = subset(sim_data, Signal == TRUE), color = "red", size = 2) +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "Integrated EPC-SPC: EWMA Chart",
                  y = "EWMA Statistic",
                  x = "Time (t)")
}
