#' Plot Integrated EPC-SPC Data
#'
#' @param sim_data A data frame generated by simulate_epc_spc()
#' @return A ggplot object displaying the Shewhart chart
#' @export
plot_spc <- function(sim_data) {
  requireNamespace("ggplot2", quietly = TRUE)

  ggplot2::ggplot(sim_data, ggplot2::aes(x = Time, y = Output)) +
    ggplot2::geom_line(color = "darkgray") +
    ggplot2::geom_hline(yintercept = sim_data$UCL[1], color = "black", linewidth = 1) +
    ggplot2::geom_hline(yintercept = sim_data$LCL[1], color = "black", linewidth = 1) +
    ggplot2::geom_hline(yintercept = 0, color = "black", linetype = "dashed") +
    ggplot2::geom_point(data = subset(sim_data, Signal == TRUE), color = "red", size = 2) +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "Integrated EPC-SPC: Shewhart Chart on Output",
                  y = "Output Deviation from Target (Yt)",
                  x = "Observation Number (t)")
}#' Plot Integrated EPC-SPC Data
#'
#' @param sim_data A data frame generated by simulate_epc_spc()
#' @return A ggplot object displaying the Shewhart chart
#' @export
plot_spc <- function(sim_data) {
  requireNamespace("ggplot2", quietly = TRUE)

  ggplot2::ggplot(sim_data, ggplot2::aes(x = Time, y = Output)) +
    ggplot2::geom_line(color = "darkgray") +
    ggplot2::geom_hline(yintercept = sim_data$UCL[1], color = "black", linewidth = 1) +
    ggplot2::geom_hline(yintercept = sim_data$LCL[1], color = "black", linewidth = 1) +
    ggplot2::geom_hline(yintercept = 0, color = "black", linetype = "dashed") +
    ggplot2::geom_point(data = subset(sim_data, Signal == TRUE), color = "red", size = 2) +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "Integrated EPC-SPC: Shewhart Chart on Output",
                  y = "Output Deviation from Target (Yt)",
                  x = "Observation Number (t)")
}
