#' Plot CUSUM Chart
#'
#' @param sim_data A data frame generated by simulate_epc_spc(spc_type = "cusum")
#' @return A ggplot object
#' @export
plot_cusum <- function(sim_data) {
  requireNamespace("ggplot2", quietly = TRUE)

  # CUSUM uses a single upper threshold (h) for both positive and negative drifts
  h_limit <- sim_data$UCL[1]

  ggplot2::ggplot(sim_data, ggplot2::aes(x = Time)) +
    ggplot2::geom_line(ggplot2::aes(y = CUSUM_P), color = "darkblue", alpha = 0.7) +
    ggplot2::geom_line(ggplot2::aes(y = CUSUM_N), color = "darkgreen", alpha = 0.7) +
    ggplot2::geom_hline(yintercept = h_limit, color = "black", linewidth = 1) +
    ggplot2::geom_hline(yintercept = 0, color = "black", linetype = "dashed") +
    ggplot2::geom_point(data = subset(sim_data, CUSUM_P > h_limit),
                        ggplot2::aes(y = CUSUM_P), color = "red", size = 2) +
    ggplot2::geom_point(data = subset(sim_data, CUSUM_N > h_limit),
                        ggplot2::aes(y = CUSUM_N), color = "red", size = 2) +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "Integrated EPC-SPC: CUSUM Chart",
                  subtitle = "Blue = Positive Drift (C+), Green = Negative Drift (C-)",
                  y = "Cumulative Sum Statistic",
                  x = "Time (t)")
}
