#' Plot EPC Control Action
#'
#' Visualizes the physical adjustments made by the automated controller over time.
#'
#' @param sim_data A data frame generated by simulate_epc_spc() or apply_system()
#' @return A ggplot object
#' @export
plot_control_action <- function(sim_data) {
  requireNamespace("ggplot2", quietly = TRUE)

  # Detect if the data came from the simulator or apply_system
  # and safely pass it to ggplot2 using the .data pronoun to avoid R CMD check warnings
  u_col <- if("ControlAction" %in% names(sim_data)) "ControlAction" else "Recommended_Action"

  ggplot2::ggplot(sim_data, ggplot2::aes(x = Time, y = .data[[u_col]])) +
    ggplot2::geom_line(color = "purple") +
    ggplot2::geom_hline(yintercept = 0, color = "black", linetype = "dashed") +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "EPC: Machine Control Action (u_t)",
                  subtitle = "The physical adjustments made to fight process drift",
                  y = "Adjustment Magnitude",
                  x = "Time (t)")
}
